# NLP intro

In [11]:
import numpy as np 

review1 = "I LOVE this book about love"
review2 = "No this book was okay"

all_words = [text.lower().split() for text in [review1, review2]]
print(all_words)

# flatten this list, can also add lists with + operator
all_words = [word for text in all_words for word in text]
print(f"Flattened all words {all_words}")

unique_words = set(all_words)
print(f"Unique words {unique_words}")

[['i', 'love', 'this', 'book', 'about', 'love'], ['no', 'this', 'book', 'was', 'okay']]
Flattened all words ['i', 'love', 'this', 'book', 'about', 'love', 'no', 'this', 'book', 'was', 'okay']
Unique words {'no', 'love', 'was', 'this', 'book', 'about', 'i', 'okay'}


In [21]:
# make a dictionary of all words
vocabulary = {word: index for index, word in enumerate(unique_words)}
print(vocabulary)

def term_frequency_vectorizer(document, vocabulary): 
    term_frequency = np.zeros(len(vocabulary))

    for word in document.lower().split():
        index = vocabulary[word]
        term_frequency[index] += 1
    
    return term_frequency

review1_term_freq = term_frequency_vectorizer(review1, vocabulary)
review2_term_freq = term_frequency_vectorizer(review2, vocabulary)

print(review1)
print(review1_term_freq)
print(review2)
print(review2_term_freq)

{'no': 0, 'love': 1, 'was': 2, 'this': 3, 'book': 4, 'about': 5, 'i': 6, 'okay': 7}
I LOVE this book about love
[0. 2. 0. 1. 1. 1. 1. 0.]
No this book was okay
[1. 0. 1. 1. 1. 0. 0. 1.]


In [24]:
import pandas as pd

bag_of_words = pd.DataFrame(
    [review1_term_freq, review2_term_freq], columns=vocabulary.keys(), dtype="int16"
)

bag_of_words


no  love  was  this  book  about  i  okay
0   0     2    0     1     1      1  1     0
1   1     0    1     1     1      0  0     1

## Feature extraction with sklearn

In [29]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer

count_vectorizer = CountVectorizer()
bag_of_words_sparse = count_vectorizer.fit_transform([review1, review2])
bag_of_words_sparse.todense(), count_vectorizer.get_feature_names()

(matrix([[1, 1, 2, 0, 0, 1, 0],
         [0, 1, 0, 1, 1, 1, 1]], dtype=int64),
 ['about', 'book', 'love', 'no', 'okay', 'this', 'was'])

In [37]:
bag_of_words = pd.DataFrame(bag_of_words_sparse.todense(), columns = count_vectorizer.get_feature_names())
bag_of_words

about  book  love  no  okay  this  was
0      1     1     2   0     0     1    0
1      0     1     0   1     1     1    1

## TF-IDF

In [39]:
tfidf_transformer = TfidfTransformer()
tfidf = tfidf_transformer.fit_transform(bag_of_words_sparse)
tfidf

<2x7 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [40]:
tfidf.todense()

matrix([[0.4078241 , 0.29017021, 0.81564821, 0.        , 0.        ,
         0.29017021, 0.        ],
        [0.        , 0.35520009, 0.        , 0.49922133, 0.49922133,
         0.35520009, 0.49922133]])

In [47]:
# creates tfidf vector in one go 
tfidf_vectorizer = TfidfVectorizer()
tfidf_words = tfidf_vectorizer.fit_transform([review1, review2]).todense()
tfidf_words

matrix([[0.4078241 , 0.29017021, 0.81564821, 0.        , 0.        ,
         0.29017021, 0.        ],
        [0.        , 0.35520009, 0.        , 0.49922133, 0.49922133,
         0.35520009, 0.49922133]])

In [44]:
tfidf_vectorizer.get_feature_names()

['about', 'book', 'love', 'no', 'okay', 'this', 'was']

In [45]:
review1

'I LOVE this book about love'

In [46]:
review2

'No this book was okay'

In [48]:
pd.DataFrame(tfidf_words, columns = tfidf_vectorizer.get_feature_names())

about     book      love        no      okay     this       was
0  0.407824  0.29017  0.815648  0.000000  0.000000  0.29017  0.000000
1  0.000000  0.35520  0.000000  0.499221  0.499221  0.35520  0.499221